/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-01-09 21:39:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Pagina_002dInicial_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"pt-br\" lang=\"pt-br\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\t\r\n");
      out.write("\t\t<meta http-equiv=\"content-language\" content=\"pt-br\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/estilo.css\" type=\"text/css\" media=\"screen\" title=\"no title\" charset=\"utf-8\"/>\r\n");
      out.write("\t\t<title>titulo</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body id=\"corpo\">\r\n");
      out.write("\t\t<div id=\"tudo\">\r\n");
      out.write("\t\t<div id=\"topo\">\r\n");
      out.write("\t\t<h1>Ambiente de teste PayPal</h1>\r\n");
      out.write("\t\t<ul id=\"lista\">\r\n");
      out.write("\t\t\t<li><a href=\"#\">ANAMACO</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">CCF</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">EFIGIE</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">PECEGE</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">UDOF</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">UNIESP</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">VETOR</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<form action=\"\" method=\"get\" id=\"busca\">\r\n");
      out.write("\t\t\t<label>Busca<input type=\"text\" name=\"busca\"/></label>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"ok\" id=\"submit\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div><!-- fim da div topo-->\r\n");
      out.write("\t\t<form action=\"Pedido\" id=\"botao\" method=\"post\">\r\n");
      out.write("\t\t\t<div id=\"principal\">\r\n");
      out.write("\t\t\t\t<h2>Moeda</h2>\r\n");
      out.write("\t\t\t\t<p>Por Favor selecione a moeda com qual deseja efetuar o pagamento</p>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\tMoeda:<select id=\"moeda\" name=\"moeda\">\r\n");
      out.write("\t\t\t\t\t<option value=\"BRL\">BRL</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"USD\">USD</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"EUR\">EUR</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h2>Produto/Quantidade(s)</h2>\r\n");
      out.write("\t\t\t\t<p>Escolha o produto que deseja comprar e informe a quantidade</p>\r\n");
      out.write("\t<div id=\"listas\">\r\n");
      out.write("\t\t<div id=\"lista1\">\r\n");
      out.write("\t\tProduto:<select id=\"produtos\" name=\"produtos\">\r\n");
      out.write("\t\t\t\t\t<option value=\"Ação\">Ação</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"computador\">Computadores</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"carro\">Carros</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\tQuantidade:<input type=\"text\" id=\"quantidade\" name=\"quantidade\" size=\"5px\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"lista2\">\r\n");
      out.write("\t\tProduto:<select id=\"produto\" name=\"produto\">\r\n");
      out.write("\t\t\t\t\t<option value=\"mouse\">Mouse</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"matrícula\">matrícula</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"gravata\">Gravata</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\tQuantidade:<input type=\"text\" id=\"quantidade2\" name=\"quantidade2\" size=\"5px\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div><!--fim da div principal-->\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div id=\"auxiliar\">\r\n");
      out.write("\t\t\t<img src=\"imagens/Apple.jpeg\" alt=\"apple\" width=\"300px\" height=\"350px\"/>\r\n");
      out.write("\t\t\t<p><a href=\"javascript:document.getElementById('botao').submit();\">Finalizar Pedido</a></p>\r\n");
      out.write("\t\t</div><!--fim da div auxiliar-->\r\n");
      out.write("\t\t<div id=\"rodape\">\r\n");
      out.write("\t\t\t<p>direitos reservados Ricardo Xavier</p>\r\n");
      out.write("\t\t</div><!--fim da div rodapé-->\r\n");
      out.write("\t\t</div><!--fim da div tudo-->\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
