/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-01-09 22:12:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.BotaoDinamico;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.LinkedList;

public final class inicio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/Cookie.js\"></script>\r\n");
      out.write("        <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">   \r\n");
      out.write("            jQuery(document).ready(function(){\r\n");
      out.write("                //Pegamos o formulário do botão\r\n");
      out.write("                var wpsBn = jQuery('#formulario');\r\n");
      out.write(" \r\n");
      out.write("                //Interceptamos o clique no botão\r\n");
      out.write("                wpsBn.click(function(e){\r\n");
      out.write("                    //Evitamos o comportamento padrão, de submeter o formulário\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write(" \r\n");
      out.write("                    //Mostramos a mensagem de redirecionamento\r\n");
      out.write("                    jQuery('<div class=\"sa_payPal_overlay\" style=\"visibility:visible;position:fixed; width:100%; height:100%; filter:progid:DXImageTransform.Microsoft.Gradient(GradientType=1, StartColorStr=\\'#88ffffff\\', EndColorStr=\\'#88ffffff\\'); background: rgba(255,255,255,0.8); top:0; left:0; z-index: 999999;\"><div style=\" background: #FFF; background-image: linear-gradient(top, #FFFFFF 45%, #E9ECEF 80%);background-image: -o-linear-gradient(top, #FFFFFF 45%, #E9ECEF 80%);background-image: -moz-linear-gradient(top, #FFFFFF 45%, #E9ECEF 80%);background-image: -webkit-linear-gradient(top, #FFFFFF 45%, #E9ECEF 80%);background-image: -ms-linear-gradient(top, #FFFFFF 45%, #E9ECEF 80%);background-image: -webkit-gradient(linear, left top,left bottom,color-stop(0.45, #FFFFFF),color-stop(0.8, #E9ECEF));display: block;margin: auto;position: fixed; margin-left:-220px; left:45%;top: 40%;text-align: center;color: #2F6395;font-family: Arial;padding: 15px;font-size: 15px;font-weight: bold;width: 530px;-webkit-box-shadow: 3px 2px 13px rgba(50, 50, 49, 0.25);box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 0px 5px;border: 1px solid #CFCFCF;border-radius: 6px;\"><img style=\"display:block;margin:0 auto 10px\" src=\"https://www.paypalobjects.com/en_US/i/icon/icon_animated_prog_dkgy_42wx42h.gif\"><h2>Aguarde alguns segundos.</h2> <p style=\"font-size:13px; color: #003171; font-weight:400\">Você está sendo redirecionado para um ambiente seguro do PayPal<br /> para finalizar seu pagamento.</p><div style=\"margin:30px auto 0;\"><img src=\"https://www.paypal-brasil.com.br/logocenter/util/img/logo_paypal.png\"/></div></div></div>').appendTo('body');\r\n");
      out.write(" \r\n");
      out.write("                    //Submetemos o formulário após a exibição da mensagem\r\n");
      out.write("                    wpsBn.submit();\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Botao.css\"></link>\r\n");
      out.write("</head>\r\n");
      out.write("   <!--  <script>GerarCookie('Dados','4050','5');</script>-->\r\n");
      out.write("<body>\r\n");
 
LinkedList<?> compra=(LinkedList<?>) request.getAttribute("compra");

      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<h1>Confirmação do pedido</h1>\r\n");
      out.write("\t<div id=\"produtos\">\r\n");
      out.write("\t\t<h2>produtos</h2>\r\n");
      out.write("\t\t<p> ");
      out.print(compra.get(4) );
      out.write("</p>\r\n");
      out.write("\t\t<p>");
      out.print(compra.get(1) );
      out.write("</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"quantidades\">\r\n");
      out.write("\t\t<h2>quantidade</h2>\r\n");
      out.write("\t\t<p>");
      out.print(compra.get(2) );
      out.write("</p>\r\n");
      out.write("\t\t<p>");
      out.print(compra.get(3) );
      out.write("</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<form method=\"post\" action=\"https://sandbox.paypal.com/cgi-bin/webscr\" style=\"top: 0px;\" class=\"paypal-button\" accept-charset=\"ISO-8859-1\" id=\"formulario\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"cmd\" value=\"_cart\"> \r\n");
      out.write("\t\t<input type=\"hidden\" name=\"upload\" value=\"1\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"lc\" value=\"BR\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"list-style-type: none\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"quantity_2\" value=");
      out.print(compra.get(3) );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"item_name_2\" value=");
      out.print(compra.get(4) );
      out.write("> \r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"item_number_2\" value=id_");
      out.print(compra.get(4));
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"amount_2\" value=\"3.00\">\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"list-style-type: none\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"quantity_1\" value=");
      out.print(compra.get(2) );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"item_name_1\" value=");
      out.print(compra.get(1) );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"item_number_1\" value=id_");
      out.print(compra.get(1) );
      out.write(">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"amount_1\" value=\"0.60\">\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<button type=\"submit\" class=\"paypal-button large\" >Comprar Agora</button>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"business\" value=\"comerciante@email.com\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"charset\" value=\"ISO-8859-1\">\r\n");
      out.write("\t    <input type=\"hidden\" name=\"currency_code\" value=");
      out.print(compra.get(0) );
      out.write(">\r\n");
      out.write("\t    <input type=\"hidden\" name=\"lc\" value=\"BR\">\r\n");
      out.write("\t   <input type=\"hidden\" name=\"notify_url\" value=\"http://95.62.66.227:8080/PayPal/Check\"> \r\n");
      out.write("\t    <input type=\"hidden\" name=\"cancel_return\" value=\"http://localhost:8080/PayPal/cancelar.jsp\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"return\" value=\"http://localhost:8080/PayPal/Final.jsp\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"teste\" name=\"invoice\" value=\"\">\r\n");
      out.write("\t</form>\r\n");
      out.write("<script>LerCookie('Dados');</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
